### ISSUE TITLE
Run nsq.js on React.js

### ISSUE THREAD

**Issue by opam22** [segmentio/nsq.js#78]
Shitty question,

Can I run this nsq client library with react.js? I use react with ES6 standard.
I already try but no luck.

Thanks.

**Comment by achille-roussel** [comment]
I think we'll need a bit more details on what you meant by "running with react.js".
Maybe give us an idea of how your application is constructed, or show us a minimal code example of what you're trying to achieve?

**Comment by thehydroimpulse** [comment]
Hey @opam22. If you're running React on the server (in Node.js) then you should be able to use nsq.js.
